- name: Set User in Git
  shell: "git config --global user.name rocko && git config --global user.email rocko@taco.com"

- name: Clone git repo
  shell: "git clone -c http.sslVerify=false {{repossh}}"
  environment:
    GIT_SSH: "{{ playbook_dir }}/roles/create_project/files/"

- name: Generate Project Yaml
  template:
    src: project.yaml
    dest: "{{playbook_dir}}/{{reponame}}/projects/templates/{{projectname}}.yaml"

- name: Add to git repo
  shell: "cd {{playbook_dir}}/{{reponame}} && git add --all"

- name: Commit to git repo
  shell: "cd {{playbook_dir}}/{{reponame}} && git commit -m '.'"

- name: Push to git repo
  shell: "cd {{playbook_dir}}/{{reponame}} && git push {{repossh}}"
  environment:
    GIT_SSH: "{{ playbook_dir }}/roles/create_project/files/"
