- name: Clone git repo
  command: git clone -c http.sslVerify=false {{ repossh }}

- name: Generate Project Yaml
  template:
    src: project.yaml
    dest: "{{playbook_dir}}/{{reponame}}/projects/templates/{{projectname}}.yaml"

- name: Add to git repo
  shell: "cd {{playbook_dir}}/{{reponame}} && git add --all"

- name: Commit to git repo
  shell: "cd {{playbook_dir}}/{{reponame}} && git commit -m '.'"

- name: Push to git repo
  shell: "cd {{playbook_dir}}/{{reponame}} && git push -c http.sslVerify=false"
